# Generated by Django 3.0.4 on 2020-05-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=50)),
                ('semester', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('eid', models.CharField(default='', max_length=50)),
                ('courses_raw', models.CharField(default='', max_length=100)),
                ('courses', models.ManyToManyField(to='projectapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('eid', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('course_raw', models.CharField(default='', max_length=100)),
                ('students_raw', models.CharField(default='', max_length=100)),
                ('professors_raw', models.CharField(default='', max_length=100)),
                ('tags_raw', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(default='', max_length=100)),
                ('image_raw', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.CharField(default='', max_length=100)),
                ('course', models.ManyToManyField(to='projectapp.Course')),
                ('professors', models.ManyToManyField(to='projectapp.Professor')),
                ('students', models.ManyToManyField(to='projectapp.Student')),
                ('tags', models.ManyToManyField(to='projectapp.Tag')),
            ],
        ),
    ]
