# Generated by Django 3.0.4 on 2020-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=50)),
                ('students', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
