# Generated by Django 3.0.4 on 2020-05-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='eid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
