# Generated by Django 3.0.4 on 2020-05-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_professor_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
